server:
  port: 8081
  servlet:
    context-path: /

spring:
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000

    show-sql: true

logging:
  level:
    org.hibernate.type: trace